// components/overlay/overlay.vue
<template>
    <div :class="show?'overlay active':'overlay'" @click="handleClick">
        <slot/>
    </div>
</template>

<script>
    import './overlay.less'

    export default {
        props: {
            show: {
                type: Boolean,
                default: false
            }
        },
        methods: {
            handleClick(e) {
                this.$emit('click', e)
            }
        }
    }
</script>

// components/overlay/overlay.jsx
import React from 'react'
import './overlay.less'

export default class extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        const show = this.props.show;
        return <div id={this.props.id} className={show ? 'overlay active' : 'overlay'} onClick={this.props.onClick}>
            {this.props.children}
        </div>
    }
}
